name: 'Build tests'
description: 'Build application'
runs:
  using: "composite"
  steps:
    - name: Remove existing build environment
      run: |
        cmake -E remove -f build

    - name: Create new build environment
      run: |
        cmake -E make_directory build

    - name: Configure CMake
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

    - name: Compile
      run: |
        cmake --build build
